Give-Your-Best/webshop

client/src/components/organisms/ImageGallery/ImageGallery.js
- addresses unexpected data in the item images causing 'access properties of undefined' error
- this applies the safe logic from the main image on the additional images
- still need to address the issue of bad data though
=> Bugfix: Unexpected data in the item images payload crashing page

client/src/components/organisms/ImageGallery/ImageGallery.js, client/src/utils/helpers.js
Relates #37 
(A few unrelated updates on the utils helpers to get things running locally with missing dummy data etc.)
Adds address rendering on the item info popup where it is provided...
=> Feature shopper address on item info popup

client/src/components/molecules/ItemsCollapsedList/ItemsCollapsedList.js, client/src/components/organisms/Dashboard/AdminItems/AdminItems.js, client/src/services/items/getAdminItems.js, client/src/services/user/getPublicUsers.js, client/src/services/user/index.js, server/routes/api/items.js, server/routes/api/users.js, server/services/items.js, server/services/users.js
The endpoint is already paginated but the performance is still not amazing and the filtering, searching and sorting is broken since it all ran entirely on the client.
This resolves a few things:
1. We no longer fetch both current and past items on load, we pull current by default and there is a new dropdown to select either the current or past items view
2. We pull the full list of donor and shopper users on load and use this list in an autocomplete/dropdown input to allow searching for a public user and pulling only items where that user is shopper or donor
Still to do are filtering by category, status, tags; sorting; filtering by item name.... (filter by status needs some clarifications)
=> 57 platform timeouts caused by long running queries

server/models/User.js, server/services/items.js, server/services/locations.js, server/services/messages.js, server/services/settings.js, server/services/tags.js, server/services/users.js
- replace `findByIdAndRemove` and `findOneAndDelete` with `findByIdAndDelete` https://mongoosejs.com/docs/api/model.html#Model.findByIdAndDelete()
- remove deprecated query option `useFindAndModify` https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options
=> Item deletion is broken with Mongoose update

client/src/components/molecules/EditForm/DonorMiniEditForm.js, client/src/components/molecules/EditForm/ItemCreateForm.js, server/controllers/authentication.js, server/models/User.js
Adds boolean property on the donor user model for toggling allow bulk item uploads with UI for admins to update.
Migration to run on release: `db.users.updateMany({ kind: 'donor' }, { $set: { canAddItemInBulk: false } })`
=> 78 bulk items handling option for donor users

client/src/components/molecules/EditForm/SizeSelector.js, client/src/pages/Item/Item.js
issue #42 
small fix when creating an item and the user has increased the quantity for a given size, but then brought it back down to zero (let's say they got it wrong initially), the quantity of 0 would have been saved to the db and falsely displayed (all-be-it greyed out and unavailable) to the user. 
This just gets rid of that altogether...
=> removing bulk-items with zero quantity during creation

client/src/pages/Item/AddBatchItemToBasket.js
Issue #42 
The order functionality for batch item was not calculating the limit correctly - classic high-school mathematics blunder of not including brackets around the operators that should take precedent :------)
=> small bug-fix batch item limit

client/src/components/molecules/EditForm/ItemCreateForm.js, client/src/components/molecules/Report/Report.js, client/src/components/organisms/Dashboard/DonorItems/DonorItems.js, client/src/pages/Item/AddBatchItemToBasket.js, client/src/utils/batchItemHelpers.js, server/models/BatchItem.js, server/services/items.js, server/services/statistics.js
Issue #42 
I was slightly apprehensive whilst making these changes as it felt "hacky", but given the time constraints and the somewhat dead-end position I found myself in (learning experience from all directions), I am confident after thorough testing with all kinds of data, that the reporting and statistics now correctly incorporates the batchItem data. 
The main idea is that I've added to the batchItem model two extra properties:
- `createdAt`
- `quantity` (which gets calculated upon creation of the batchItem)
Using these two extra properties I basically aggregate the `quantity` and sum them up accordingly to the item counts.
The reason there are so many different `pipelines` for the `aggregateBatchItemGroupData`, is because the method for how to count the sums were a bit different …
=> Statistics & Report data now includes batch items

client/src/components/molecules/Report/Report.js
#42  
Finishing touches, but the "available" column was missing zero values, instead it had an empty string.
=> fix report not showing zeros for available

client/src/components/molecules/ItemCardLong/ItemCardLong.js
Some items e.g. 'other' or 'accessories' may not have a size.
=> Added conditional size rendering to order view

client/src/components/organisms/Dashboard/AdminItems/AdminItems.js
#42 
There was a bug whenever an item was being deleted from the admin-items dashboard which was already shopped and had a bulk-id.
=> handle deleting ordered items that have bulk id

server/services/items.js, server/tasks/index.js, server/tasks/processLostBatchItems.js
#42 
Whenever a shopper adds a batch-item to their basket and refreshes their webpage, that item gets rendered lost from the perspective of the code since the state is not persisted and there is no way for the shopper to get it back at the moment.
Until we address the state-persistence issue, this task scheduler - maybe run once every 12 hours or 24 hours - will:
- fetch all the lost-batch-items
- update their respective batchItem size & quantity
- delete the lost-item
Tested on dev environment by simply calling the inner logic manually and it seems to be working - curious to get it setup with a task scheduler.
=> Task-Scheduler for lost-batch-items

client/src/components/molecules/Report/Report.js
Disabling the ability to generate full-report as it crashes in Production - temporary solution until the reporting is addressed more thoroughly.
=> Disable generating report without a range-date

server/models/Item.js, server/services/items.js
Whenever a batchItem has no more items, the status is now changed to `empty` on its corresponding templateItem, which subsequently gets removed from the available shop items.
The batchItem can be viewed by the donor in their "past items" and if they wish to edit it again, to add quantity, it will come back in the shop accordingly.
=> hide batchItems from shop when their quantity is 0

client/src/components/molecules/EditForm/DonorMiniEditForm.js, client/src/components/molecules/EditForm/EditForm.styles.js, client/src/components/molecules/EditForm/ItemCreateForm.js, client/src/components/molecules/EditForm/ItemMiniEditForm.js, server/controllers/authentication.js, server/models/User.js
Approved & permitted donor can now set tags on items either during creation or editing...
Admins can permit donors to perform item tagging with the new `caAddItemTags` flag
=> 134 item tagging

server/services/reports.js
including the excel file extension when saving the report in the db, so that when it is retrieved and sent via email, the user can easily open it.
=> adding excel file extension to historic report

server/services/items.js
Regarding issue #170 
This filter already exists on the 'getShopNotifications' and testing it locally, it seems to work correctly in hiding a given donor's (in this case the GYB_HQ donor) items. 
It seems to not have been applied to the 'Account Notifications', so this is just adding it there too in case some items were spotted there.
If the users are able to produce examples of this not working on Production, I can take another look at it.
=> adding a filter to account notifications to exclude gyb-donor items

client/src/components/molecules/DonorOrdersList/DonorOrdersList.js, client/src/components/molecules/ItemCardLong/ItemCardLong.js
I have found a scenario where the 'mark as sent' button creates a problem.
If a donor account does not have the ability to see the shopper's address i.e. User can view shopper address = false  AND user has not shared the address directly AND the address has not yet been assigned AND for some reason (user error) the donor nonetheless presses the 'Mark as Sent'. This will by-pass sending it to GYB via the admin account, in which case, that item (from the perspective of the code & db) will be sent directly to the user (since the db knows the shopperId's address despite the fact that donor does not know it).
In reality this would mean this:
- Shopper shops an item
- Donor accidentally presses 'mark as sent' before having the item's delivery address assigned to it
- The item is 'sent' to the …
=> whenever address is not present, hide mark-as-sent button

client/src/components/molecules/ItemCardLong/ItemCardLong.js
ensuring the onAddressVisibilityChange is present as a function, since in some scenarios its not needed and therefore not passed through into the `ItemCardLong` component.
=> adding error safety around prop that shows the address

client/src/pages/Basket/Basket.js, client/src/utils/constants.js
Issue #172 
This code will auto-assign the item's `sendVia` property to that of GYB office's location_id. 
It will also notify the donor that they need to dispatch an item. 
Seeking thoughts & advice on how to better handle the GYB office's location ID. 
`
let updateData = {
sendVia: '6539040db9c7d96390fe8f2e', // need to find a better way to get this ID
'statusUpdateDates.gybAssignedDate': getDate(),
};
`
In the Basket view, we don't have a simple way to fetch the location by name (which could be a nice-to-have). Perhaps there's even better ways to handle it.
For now, I'll keep it like this until we / I come up with a better idea as I progress through the other related task.
Tested locally with the following scenarios:
1. TrustedDonor: TRUE && showAddress: FALSE -> No address is shown, …
=> auto assign untrusted donor items to gyb address upon checking out

client/src/components/organisms/Dashboard/Notifications/Notifications.js, client/src/services/user/evaluateDonorTrust.js, client/src/services/user/index.js, server/controllers/users.js, server/routes/api/users.js, server/services/users.js
Issue #172 
This PR addresses the auto-trusting donors upon an admin marking their items as 'received' in the [Account Notifications].
The decision to make the `evaluateDonorTrust` as a backend service was mainly to avoid having to make multiple fetch calls on the frontend:
- get the full item (itemId)
- get the donor user (item.donorId)
- fetch/count all items with donorId (whose status is one in the verified status)
- then make the judgement whether to update or not.
Instead of performing all of the above in the client, I decided to perform these tasks on the backend. 
Thoroughly tested locally in various scenarios.
Feedback is always welcome :)
=> 172 auto assign untrusted items

client/src/components/molecules/DonorOrdersList/DonorOrdersList.js
The `Mark as sent` button was conditionally rendered by the logic within the `View delivery address` button.
A user got confused where the `Mark as sent` button went, given they had already previewed the address on the item, went away to package it up and as they had reloaded the page upon their arrival back, the `Mark as sent` button was gone too (in actuality: it just needed to be triggered again by clicking the `View delivery address`). 
This PR doesn't solve the underlying clunkiness of this issue but simply makes it slightly more user-friendly by always having the `Mark as sent` visible (instead of conditionally rendered), but instead, it now `disables` the button with an added tooltip to give the user the extra instruction i.e. to press the `View delivery address` to trigger the …
=> added a tooltip to the mark-as-sent button for user clarity

client/src/components/molecules/DonorOrdersList/DonorOrdersList.js, server/services/users.js
The `Mark as sent` button was conditionally rendered by the logic within the `View delivery address` button.
A user got confused where the `Mark as sent` button went, given they had already previewed the address on the item, went away to package it up and as they had reloaded the page upon their arrival back, the `Mark as sent` button was gone too (in actuality: it just needed to be triggered again by clicking the `View delivery address`). 
This PR doesn't solve the underlying clunkiness of this issue but simply makes it slightly more user-friendly by always having the `Mark as sent` visible (instead of conditionally rendered), but instead, it now `disables` the button with an added tooltip to give the user the extra instruction i.e. to press the `View delivery address` to trigger the …
=> added tooltip to the mark-as-sent button for user clarity

.github/workflows/node.js.yml, client/src/components/molecules/EditForm/ShopSettingsEditForm.js, client/src/components/molecules/ItemCardLong/ItemCardLong.js, client/src/components/organisms/Dashboard/DonorItems/DonorItems.js, server/services/items.js
Request from the GYB team to remove the untrusted donor constraints that were added last year.
The comment reads:
> Hi team, hope you’re all well and enjoying the longer days! We have had a review of the New Donor parcel checking process - thank you so much for setting that up as it was such a necessary measure after the august riots.
We have not had any issues with new donor parcels coming through HQ over the last 6 months, so we’d like to go ahead and remove this extra measure for now, so new donors will behave the same as all donors, without having to send the first 5 parcels via HQ, and with no limit to the amount of items they can upload from the start.
I’m not sure how this was set up, but it would be great to keep it as a feature we’d be able to ‘switch on’ again if needed in the …
=> commenting out donor limit constraint

server/services/reports.js, server/tasks/generateHistoricReport.js
Added a new report, to run weekly (on Mondays), that generates Names & Emails of shoppers created in the last week who are based in London or Greater London.
Filter query:
- Kind: Shopper
- CreatedAt (In the last 7 days)
- Postcode: London or Greater London (using a long regex)
Output:
-  `FirstName, LastName, Email`
=> added a new report for weekly shoppers in london
