- README.md
This guide should live elsewhere but until that time comes, here it is :)
> Update readme with db connection info

- client/src/utils/constants.js
Added 3XL and 4XL in clothing sizes:
> add more clothing sizes

- client/src/components/molecules/ItemsCollapsedList/ItemsCollapsedList.js
- client/src/components/organisms/Dashboard/AdminItems/AdminItems.js
- client/src/services/items/getAdminItems.js
- server/routes/api/items.js
- server/services/items.js
This work introduces server side pagination on the admin items endpoints with integration into the relevant client side components - this is working well but needs a more robust implementation soon with dedicated components and patterns etc. 👍🏼
> 52 admin items endpoint timeouts

- client/src/components/organisms/Dashboard/Settings/Settings.js
- server/routes/api/users.js
> 57 platform timeouts caused by long running queries

- client/package.json
- server/config/cloudinary.js
- server/utils/cloudinary.js
> 72 cloudinary config is broken

- package-lock.json
- package.json
- runner.js
- server/models/LogEntry.js
- server/services/items.js
- server/tasks/index.js
- server/utils/transport.js
- adding a deicated logging service for the task runner with mongo db transport...
> 38 implement cron jobs

- client/src/utils/sizeOptions.js
trivial change but I missed this in my previous PR.
> change label for accessories & other category

- client/src/components/organisms/Banners/Banner.js
- client/src/components/organisms/Banners/Banner.styles.js
- client/src/components/organisms/Banners/index.js
- client/src/components/organisms/Header/Header.js
- server/models/Banners.js
- server/routes/api/index.js
- server/services/banners.js
Adds a banner alert display implementation with DB integration (we should be able to add alerts to the db in x format and show them without further changes to the codebase)
> Hotfix holiday banner

- client/src/components/organisms/Banners/Banner.js
- client/src/components/organisms/Banners/Banner.styles.js
- client/src/components/organisms/Banners/index.js
- client/src/components/organisms/Header/Header.js
- server/models/Banners.js
- server/routes/api/index.js
- server/services/banners.js
This gets the hotfix on release branch on to staging 👍🏼 
- Adds a banner component to the front page
- messages can be aded direct to the db currently
> 51 home page banner notice

- client/src/components/organisms/Logout/Logout.js
- client/src/utils/resetBasketItems.js
> 97 logout client crash

- client/src/components/molecules/OrdersList/OrdersList.js
#42 
Now handles bulk-items when cancelling an order:
1. updates parent-bulk-item with the correct quantity 
2. deletes the child-bulk-item that is being cancelled
> #42 cancel order for bulk-items

- client/src/components/molecules/EditForm/DonorMiniEditForm.js
Whilst the bulk feature is being finalized, it's agreed with Haydn, to free up the Staging branch, we'll push the code to Production but hide it from actually being accessible.
> hiding bulk feature for time being

- server/services/items.js
fix typo preventing 'shipped to gyb' items appearing in the current items view...
> 111 Admin current items view bug

- server/services/statistics.js
#42 - bulk feature
item count fix for when there are no batch items
> item count fix 

- client/src/components/molecules/EditForm/DonorMiniEditForm.js
in preparation for releasing live
> re-enabling batch item mode

- client/src/components/molecules/ItemCardLong/ItemCardLong.js
- client/src/components/organisms/Dashboard/AdminItems/AdminItems.js
in a rare case where when deleting item from admin dashboard which has batchId but isn't the parent-batch-item
> bug-fix when deleting item from admin dashboard which has batchId

- client/src/components/molecules/MessagesList/MessagesList.js
- client/src/components/molecules/MessagesList/MessagesList.styles.js
- client/src/components/organisms/Dashboard/AdminMessages/AdminMessages.js
- client/src/services/messages/archiveMessageThread.js
- client/src/services/messages/deleteMessageThread.js
- client/src/services/messages/index.js
- client/src/services/messages/restoreMessageThread.js
- server/routes/api/messages.js
Adds buttons / actions to the admin messages view to allow for manually archiving, restoring, and permanently deleting threads
> 80 message deletion

- client/src/components/molecules/EditForm/DonorMiniEditForm.js
- client/src/components/molecules/ItemCardLong/ItemCardLong.js
- server/controllers/authentication.js
- server/models/User.js
- adds new property on donor users
- allow admins to toggle the new property
- allow donors with the property extra permission
> 106 allow admin approved donors to view shopper addresses

- server/services/reports.js
- server/services/statistics.js
Some of the data points for shopper & donor within the historic data report was not correctly fetching the values that were intended, this fix is to address those, namely, I've fixed:
1. Total number of shoppers who have shopped
2. Total number of donors who have donated
> refactoring shopper & donor data for historic reports

- client/src/Routes.js
- client/src/components/ProtectedRoute.js
- client/src/components/organisms/Header/Header.js
- client/src/pages/Home/Home.js
- client/src/pages/Login/Login.js
- server/controllers/authentication.js
Urgent app disable with temp messaging...
App needs to be accessible to admins but not shoppers/donors
- signup is blocked
- login is available but only for admins
- menus are hidden
- banner is shown
- special home page messaging is shown
- dashboard is still fully functional for logged in admins
> disable login and authentication for all but admin users

- client/src/Routes.js
- client/src/components/ProtectedRoute.js
- client/src/components/atoms/Button/Button.js
- client/src/components/molecules/ItemCardLong/ItemCardLong.js
- client/src/components/organisms/Dashboard/ApproveRequests/ApproveRequests.js
- client/src/components/organisms/Dashboard/DonorItems/DonorItems.js
- client/src/components/organisms/Header/Header.js
- client/src/pages/Home/Home.js
- client/src/pages/Login/Login.js
- client/src/utils/helpers.js
- server/controllers/authentication.js
- server/models/User.js
- server/services/items.js
Restore all the out of service state and add new logic for handling donor not yet trusted 
- a donor will no longer be automatically trusted following approval of three items
- a donor can upload no more than 5 items when not marked trusted
- all items shopped from an untrusted donor MUST be dispatched via gyb whether shopper requests it or not
- admins will decide when to mark a donor as trusted having inspected x number of items shipped
> 159 restore operations with extra measures

- server/services/items.js
Shop notification items fix - exclude where trusted donor is not set (legacy cases)
> 159 restore operations with extra measures bugfix

- server/services/items.js
- refine the donor items filtering populated shopper data for better ordering
> 159 restore operations with extra measures bugfix 

- server/services/items.js
> Donor items processing grouping bugfix

- server/services/items.js
> Donor items processing null document bugfix

- server/services/items.js
> Super user donor veiwable fields bugfix

- client/src/pages/Basket/Basket.js
- server/services/items.js
> Address in item shopped emails bug

- server/services/items.js
Just a small start in solving the problem.
> return firstname instead of email for untrusted donor

- client/src/components/organisms/Dashboard/DonorItems/DonorItems.js
- client/src/components/organisms/Dashboard/DonorItems/DonorItems.styles.js
> 190 adds copy and new styled alert component

- server/services/users.js
Issue #193 
Code that sends an email to the donor upon approving them (once they have had 5 items approved). 
Will double check with the team on the exact wording of the email.
> send email to donor upon approval

- package-lock.json
- package.json
- server/services/mail.js
- server/services/reports.js
- server/tasks/generateHistoricReport.js
- server/tasks/index.js
Chloe has asked for a monthly, automated email to be sent that contains a csv file of all the latest shoppers info for the following fields:
`First Name	Last Name	Email Address	Full Address	Post Code`
To achieve this, I have refactored and re-used the code for generating the historic report.
For now, this is suffice, if in the future there are other reports to be generated in this fashion, it might be useful to refactor a bit more thoroughly e.g. the current naming is a bit lazy/messy from my side.
> Generating a Monthly shoppers csv 

- client/src/components/organisms/Footer/Footer.js
- package-lock.json
Links are switched to hosting on cloudinary
also upgrade dependences security...
> 200 fix links for how to guides

- client/src/components/molecules/EditForm/ShopSettingsEditForm.js
- client/src/components/organisms/Dashboard/Notifications/Notifications.js
- client/src/pages/Basket/Basket.js
- server/services/items.js
Bug fix for address not being displayed to Donors in some cases. This was leftover from reverting back changes that involved adding constraints to the donors.
> Bug fix: donor address not showing

- client/src/components/molecules/EditForm/ShopperCreateForm.js
- client/src/components/molecules/EditForm/ShopperFields.js
- client/src/components/molecules/EditForm/ShopperMiniEditForm.js
- client/src/components/molecules/EditForm/UserEditForm.js
fix so that shopper can select limits on signup but not in account, and admins can edit any time...
> Fix the thing
